### ISSUE TITLE
Error :  Something went wrong

### ISSUE THREAD

**Issue by chetanpatidar11** [hyper-trophy/VaccASSIST#5]
from yesterday onward after 20-30 cycles of refresh or may be at the time of slot open it was giving error somethings went wrong ......Is there is any security updated on Co-win ?? It is working fine before i am trying with V3 and V4 both working fine other than above error.

**Comment by chetanpatidar11** [comment]
![Screenshot from 2021-05-23 09-17-34](https://user-images.githubusercontent.com/79536420/119249471-6b165600-bbb6-11eb-877b-480556669c5a.png)

**Comment by hyper-trophy** [comment]
I guess the Cowin website is a limiting the number of requests per IP and that's why this error is coming. To find the solution of this in the new update that is version 4.2 of my extension, I have included an option called refresh rate. So if you Can specify after how much seconds the page needs to be refreshed.  So if you specify Request rate, something like 10, there will be only one request every 10 seconds and the frequency of that error will be reduced.
 Even I can see that you are using an older version of my extension. I recommend you to please update to the latest version that is 4.2.

**Comment by chetanpatidar11** [comment]
now after update issue is resolved.
