### ISSUE TITLE
Getting error 'Something went wrong'

### ISSUE THREAD

**Issue by GauravTaneja12** [hyper-trophy/VaccASSIST#8]
I am getting error 'something went wrong' in all the versions V4.1, V4.2, V4.3, V4.4, V4.5 and due to this, i can't get to know that it is logged out or not.  I have also tried it in 3 laptops. Please fix this issue.
You have done the excellent coding.

**Comment by hyper-trophy** [comment]
In the event that you're getting the blunder "something went wrong" it has nothing to do with my extension it is simply because of the Co-win site who is impeding restriction to an excessive number of requests. So regardless of whether you do it manually you will in any case get a similar error. A few arrangements you can attempt: 
▪️ Set the refresh rate more than or equivalent to 10. 
▪️ Turn mobile hotspot on off in the event that you are utilizing mobile data or reset your Wi-Fi during this error. 
▪️ Logout, close your browser, and re-login once more. 
▪️ Clear your browser cookies and restart it.

**Comment by GauravTaneja12** [comment]
Thanks for your reply and suggestions.

**Comment by GauravTaneja12** [comment]
I did all the arrangements but still sometimes getting same error and also couldn't identified when it has been logged out as it was keep refreshing and when i refresh the page it was logged out and all the centers got booked. Can you please suggest me anything or change in code Thanks

**Comment by hyper-trophy** [comment]
You just check the website under45.in and see their previous messages, you will get an idea about when the slots actually open in your area now sit around at that time with my extension started.
Just hope the slot will get booked before error.

I suspect that you are running the extension for whole day (or substantially for longer periods in hours) and this is not actually possible because the cowin servers are going to limit the number of request. 

That's why I request you to start the extension around the time when slots are opening in your area.

**Comment by GauravTaneja12** [comment]
okay, thanks a lot for your reply and suggestions

**Comment by hyper-trophy** [comment]
SOlved download V6
